---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 15314.
--- DateTime: 2025-01-03 16:10
---
--参数列表：优惠券id/用户id/订单id
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--库存key
local stockKey = 'seckill:stock:' .. voucherId

--订单Key
local orderKey = 'seckill:order:' .. voucherId

--脚本业务
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

--判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

--扣库存，下单并保存用户
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)

--发送消息到消息队列中
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId,
'id', orderId)

return 0